@forwardfun plot_autocorr
@forwardfun plot_compare
@forwardfun plot_density
@forwardfun plot_dist
@forwardfun plot_elpd
@forwardfun plot_energy
@forwardfun plot_ess
@forwardfun plot_forest
@forwardfun plot_hpd
@forwardfun plot_joint
@forwardfun plot_kde
@forwardfun plot_khat
@forwardfun plot_loo_pit
@forwardfun plot_mcse
@forwardfun plot_pair
@forwardfun plot_parallel
@forwardfun plot_posterior
@forwardfun plot_ppc
@forwardfun plot_rank
@forwardfun plot_trace
@forwardfun plot_violin
