@datafun plot_autocorr
@datafun plot_density
@datafun plot_dist
@datafun plot_energy
@datafun plot_ess
@datafun plot_forest
@datafun plot_hpd
@datafun plot_joint
@datafun plot_kde
@datafun plot_loo_pit
@datafun plot_mcse
@datafun plot_pair
@datafun plot_parallel
@datafun plot_posterior
@datafun plot_ppc
@datafun plot_rank
@datafun plot_trace
@datafun plot_violin
