name: format-check

on:
  push:
    branches:
      - 'main'
      - 'release-'
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: actions/checkout@v1
      - name: Install JuliaFormatter
        run: |
          using Pkg
          Pkg.add("JuliaFormatter")
        shell: julia --color=yes {0}
      - name: Format code
        run: |
          using JuliaFormatter
          format("."; verbose=true)
        shell: julia --color=yes {0}
      - name: Suggest formatting changes
        uses: reviewdog/action-suggester@v1
        if: github.event_name == 'pull_request'
        with:
          tool_name: JuliaFormatter
          fail_on_error: true
